steps:

# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--build-arg', 'BUILD_ID=${_BUILD_ID}', '-t', 'gcr.io/$PROJECT_ID/SERVICE-NAME:$COMMIT_SHA', '.', '--no-cache']

# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/SERVICE-NAME:$COMMIT_SHA']

# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'flask-assigment'
  - '--image'
  - 'gcr.io/$PROJECT_ID/SERVICE-NAME:$COMMIT_SHA'
  - '--region'
  - 'asia-south1'
  - '--platform'
  - 'managed'
images:
- 'gcr.io/$PROJECT_ID/SERVICE-NAME:$COMMIT_SHA'
substitutions:
    _BUILD_ID: xyz # default value