steps:

# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--build-arg', 'BUILD=${_DEPLOY_REGION}', 'PROJECT_ID=$PROJECT_ID', 'PROJECT_NUMBER=$PROJECT_NUMBER', 'REVISION_ID=$REVISION_ID', 'COMMIT_SHA=$COMMIT_SHA', '-t', 'gcr.io/$PROJECT_ID/SERVICE-NAME:$COMMIT_SHA', '.']

# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/SERVICE-NAME:$COMMIT_SHA']

# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'flask-assigment'
  - '--image'
  - 'gcr.io/$PROJECT_ID/SERVICE-NAME:$COMMIT_SHA'
  - '--region'
  - 'asia-south1'
  - '--platform'
  - 'managed'
images:
- 'gcr.io/$PROJECT_ID/SERVICE-NAME:$COMMIT_SHA'

